// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;
public class SimpalsRegistrationRandomTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void simpalsRegistrationRandomTest() {
    driver.get("https://simpalsid.com/user/register");
    driver.manage().window().setSize(new Dimension(992, 912));
    driver.findElement(By.name("email")).click();
    vars.put("email", js.executeScript("return \"Irina\" + new Date().getDate() + (new Date().getMonth() +1) + new Date().getFullYear() + \"time\" + new Date().getHours()  + new Date().getMinutes() + new Date().getSeconds() + \"@_.com\""));
    System.out.println(vars.get("email").toString());
    driver.findElement(By.name("email")).sendKeys(vars.get("email").toString());
    driver.findElement(By.name("login")).click();
    vars.put("login", js.executeScript("return \"irina\" + Math.floor(Math.random()*1000)"));
    System.out.println(vars.get("login").toString());
    driver.findElement(By.name("login")).sendKeys(vars.get("login").toString());
    driver.findElement(By.name("password")).click();
    driver.findElement(By.cssSelector(".login__wrapper")).click();
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("irina1807");
    driver.findElement(By.id("agree-rules")).click();
    driver.findElement(By.cssSelector(".login__form__footer__submit")).click();
  }
}
